# Site settings
title: PlanetLotus
email:
description: > # this means to ignore newlines until "baseurl:"
    Side project ramblings, lessons learned, and ravings about awesome software.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username:
github_username:  PlanetLotus

# Build settings
markdown: kramdown
syntax-highlighting:
    enabled: true
    css: syntax.css

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            comments: true

gems:
    - jekyll-seo-tag
